import type { EnvironmentPreset, TemplateSettings } from "./types";

export const DEFAULT_MODEL_URL = "/models/model.glb";

export const MODEL_PATH_PRESETS = [
  "/models/model.glb",
  "/models/character.glb",
  "/models/scene.glb",
  "/models/prop.glb",
];

export const ENVIRONMENT_OPTIONS: EnvironmentPreset[] = [
  "studio",
  "city",
  "warehouse",
  "apartment",
  "lobby",
  "park",
  "forest",
  "sunset",
  "dawn",
  "night",
];

export const DEFAULT_SETTINGS: TemplateSettings = {
  modelUrl: DEFAULT_MODEL_URL,
  useDraco: false,
  position: [0, 0, 0],
  rotation: [0, 0, 0],
  scale: [1, 1, 1],
  uniformScale: 1,
  autoCenter: true,
  groundAlign: true,
  showTransformGizmo: false,
  transformMode: "translate",
  fitOnLoad: true,
  fitMargin: 1.9,
  cameraMode: "perspective",
  fov: 45,
  orthographicZoom: 90,
  autoRotate: false,
  enablePan: true,
  enableZoom: true,
  minDistance: 0.2,
  maxDistance: 80,
  backgroundColor: "#111417",
  showGrid: true,
  gridSize: 12,
  gridCellSize: 0.5,
  gridFadeDistance: 18,
  showAxes: false,
  axesSize: 3,
  showFloor: true,
  floorY: 0,
  floorColor: "#20252a",
  castShadow: true,
  receiveShadow: true,
  ambientIntensity: 0.65,
  keyLightIntensity: 3.2,
  keyLightPosition: [4, 6, 5],
  environmentEnabled: false,
  environmentPreset: "studio",
  environmentBackground: false,
  toneMapping: "aces",
  exposure: 1,
  fogEnabled: false,
  fogNear: 8,
  fogFar: 32,
  wireframe: false,
  doubleSided: false,
  overrideMaterial: false,
  materialColor: "#f5f7fb",
  roughness: 0.62,
  metalness: 0.08,
  animationName: "",
  animationPlaying: true,
  animationSpeed: 1,
  animationLoop: "repeat",
  showStats: false,
};
